module.exports = {
	"AutoDownload" : require("./source/autodownload.js"),
	"Button" : require("./source/button.js"),
	"ComponentCanvas" : require("./source/component-canvas.js"),
	"ComponentClickDragCamera" : require("./source/component-click-drag-camera.js"),
	"ComponentEditFloat" : require("./source/component-editfloat.js"),
	"ComponentEditOrbitalCamera" : require("./source/component-editorbitalcamera.js"),
	"ComponentEditVec2" : require("./source/component-editvec2.js"),
	"ComponentEditVec3" : require("./source/component-editvec3.js"),
	"ComponentEditVec4" : require("./source/component-editvec4.js"),
	"ComponentFps" : require("./source/component-fps.js"),
	"ComponentMouseKeyboardCamera" : require("./source/component-mouse-keyboard-camera.js"),
	"Format" : require("./source/format.js"),
	"Text" : require("./source/text.js"),
};
