
import { Base64ToUint8Array, Base64ToFloat32Array } from './../core/base64.js';
import ModelWrapperFactory from './../webgl/modelwrapper.js';
import ModelDataStream from './../webgl/modeldatastream.js';

export default function(in_webGLState){
	return ModelWrapperFactory(
		in_webGLState, "POINTS", 7, {
			"a_sphere" : ModelDataStream(in_webGLState, "FLOAT", 4, Base64ToFloat32Array("P6AAAD7ds9c+gdENP7CnmEAQAAA+3bPXveg6uD+HbS0/QAAAP6ZG4T5D7xU/qXSIP+AAAD+mRuG9j9gxP4wWh0AwAAA/pkbhvrrOVD9bu/U/oAAAQAqQZ75D7xU/fl1AQBAAAEAKkGe+xZJAP1fIFQ=="), "STATIC_DRAW", false),
			"a_objectID" : ModelDataStream(in_webGLState, "BYTE", 2, Base64ToUint8Array("AAEAAgADAAQABQAGAAc="), "STATIC_DRAW", true),
			"a_colour" : ModelDataStream(in_webGLState, "BYTE", 3, Base64ToUint8Array("MzOAMzOAMzOAMzOAMzOAMzOAMzOA"), "STATIC_DRAW", true),
			"a_plane0" : ModelDataStream(in_webGLState, "FLOAT", 4, Base64ToFloat32Array("AAAAAAAAAAA/gAAAP6B0QwAAAAAAAAAAP4AAAD9i+KkAAAAAAAAAAD+AAAA/mH3jAAAAAAAAAAA/gAAAP24E+gAAAAAAAAAAP4AAAD8imNYAAAAAAAAAAD+AAAA/TwQ7AAAAAAAAAAA/gAAAPx024A=="), "STATIC_DRAW", false),
			"a_plane1" : ModelDataStream(in_webGLState, "FLOAT", 4, Base64ToFloat32Array("AAAAAAAAAAC/gAAAP6B0QwAAAAAAAAAAv4AAAD9i+KkAAAAAAAAAAL+AAAA/mH3jAAAAAAAAAAC/gAAAP24E+gAAAAAAAAAAv4AAAD8imNYAAAAAAAAAAL+AAAA/TwQ7AAAAAAAAAAC/gAAAPx024A=="), "STATIC_DRAW", false),
			"a_plane2" : ModelDataStream(in_webGLState, "FLOAT", 4, Base64ToFloat32Array("P4AAAAAAAAAAAAAAPwAAAD+AAAAAAAAAAAAAAD8AAAA/gAAAAAAAAAAAAAA/AAAAP4AAAAAAAAAAAAAAPwAAAD+AAAAAAAAAAAAAAD8AAAA/gAAAAAAAAAAAAAA/AAAAP4AAAAAAAAAAAAAAPwAAAA=="), "STATIC_DRAW", false),
			"a_plane3" : ModelDataStream(in_webGLState, "FLOAT", 4, Base64ToFloat32Array("v4AAAAAAAAAAAAAAPwAAAL+AAAAAAAAAAAAAAD8AAAC/gAAAAAAAAAAAAAA/AAAAv4AAAAAAAAAAAAAAPwAAAL+AAAAAAAAAAAAAAD8AAAC/gAAAAAAAAAAAAAA/AAAAv4AAAAAAAAAAAAAAPwAAAA=="), "STATIC_DRAW", false),
			"a_plane4" : ModelDataStream(in_webGLState, "FLOAT", 4, Base64ToFloat32Array("PwAAAD9ds9cAAAAAPwAAAD8AAAA/XbPXAAAAAD8AAAA/AAAAP12z1wAAAAA/AAAAPwAAAD9ds9cAAAAAPwAAAD8AAAA/XbPXAAAAAD8AAAA/AAAAP12z1wAAAAA/AAAAPwAAAD9ds9cAAAAAPwAAAA=="), "STATIC_DRAW", false),
			"a_plane5" : ModelDataStream(in_webGLState, "FLOAT", 4, Base64ToFloat32Array("PwAAAL9ds9cAAAAAPwAAAD8AAAC/XbPXAAAAAD8AAAA/AAAAv12z1wAAAAA/AAAAPwAAAL9ds9cAAAAAPwAAAD8AAAC/XbPXAAAAAD8AAAA/AAAAv12z1wAAAAA/AAAAPwAAAL9ds9cAAAAAPwAAAA=="), "STATIC_DRAW", false),
			"a_plane6" : ModelDataStream(in_webGLState, "FLOAT", 4, Base64ToFloat32Array("vwAAAD9ds9cAAAAAPwAAAL8AAAA/XbPXAAAAAD8AAAC/AAAAP12z1wAAAAA/AAAAvwAAAD9ds9cAAAAAPwAAAL8AAAA/XbPXAAAAAD8AAAC/AAAAP12z1wAAAAA/AAAAvwAAAD9ds9cAAAAAPwAAAA=="), "STATIC_DRAW", false),
			"a_plane7" : ModelDataStream(in_webGLState, "FLOAT", 4, Base64ToFloat32Array("vwAAAL9ds9cAAAAAPwAAAL8AAAC/XbPXAAAAAD8AAAC/AAAAv12z1wAAAAA/AAAAvwAAAL9ds9cAAAAAPwAAAL8AAAC/XbPXAAAAAD8AAAC/AAAAv12z1wAAAAA/AAAAvwAAAL9ds9cAAAAAPwAAAA=="), "STATIC_DRAW", false)
		}
	);
}
